### ISSUE TITLE
Need to have a proper markdown extractor for offline use

### ISSUE THREAD

**Issue by geekodour** [geekodour/gitpushblog#22]
Right now the offline markdown files inside the `content` directory should follow this format:
```
Title: This is a new title
Rest of the post goes here, more text
## written in markdown
- 1
- 2
``` 
the `getOfflineFileContents` method reads files inside `content`, converts the markdown contents to `post` object 
```json
post obj {"body":"i am body","title":"i am the title"}
```
then we can use the the [github-blog-api's  `createPost` method](https://github.com/geekodour/github-blog-api/blob/master/src/index.js#L227-L251) to create new issue *(post)*.
Right now, it's just plain old of slice and splits to get the `title` and `body`, need a more proper and more predictable way to do this. Label support is also something that we can add to the `post` object.

See the code related to this [issue here](https://github.com/geekodour/gitpushblog/blob/master/scripts/utils.js#L88-L92)

**Comment by geekodour** [comment]
The folks at graphcool have a very [nice way of adding metadata](https://raw.githubusercontent.com/graphcool/content/dev/content/tutorials/clients/graphql-cra-apollo/create-graphql-react-apps-with-apollo-client.md) to their markdown files

**Comment by CodeDotJS** [comment]
@geekodour 
can you comment the link to the main repository instead of showing the raw file?

**Comment by geekodour** [comment]
@CodeDotJS  link to another post: https://github.com/graphcool/content/blob/dev/content/tutorials/clients/relay-modern/getting-started.md

**Comment by geekodour** [comment]
this library completely solves the problem: https://github.com/scottstanfield/markdown-to-json

**Comment by geekodour** [comment]
test comment
